<?php

function dna_menu() {
    $items['dna_entry'] = array(
        'title' => 'Generate DNA Strand',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_result'] = array(
        'title' => 'DNA Result',
        'page callback' => 'dna_display_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['user_input'] = array(
        '#title' => 'Nucleotides',
        '#type' => 'textfield',
        '#description' => t('Enter any combination of the Nucleotides A, T, C or G with no spaces.'),
        '#element_validate' => array('element_validate_input'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}

function dna_form_submit() {

}

function element_validate_input($element) {

}

function dna_find_matches($user_nucleotides) {
    //create array of characters for UN

    //create empty variable for results

    //for each nucleotide in array

    //conditinal statement identifies nucleotide and matches it to its neccesary pair, then pushes paired nucleotide into results string

    //create session variable key for results.

    //remember to add return statement of results string for test

}

function dna_display_result() {

}
