<?php

function dna_menu() {
    $items['dna_entry'] = array(
        'title' => 'Generate DNA Strand',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_result'] = array(
        'title' => 'DNA Result',
        'page callback' => 'dna_display_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {

}

function dna_form_submit() {

}

function element_validate_input($element) {

}

function assemble_dna($user_nucleotides) {
    //create array of characters for UN

    //create empty array for results

    //for each nucleotide in array

    //conditinal statement identifies nucleotide and matches it to its neccesary pair, then pushes paired nucleotide into results array

    //create session variable key for results.

}

function dna_display_result() {

}
