<?php

function dna_menu() {
    $items['dna_entry'] = array(
        'title' => 'Generate DNA Strand',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['dna_result'] = array(
        'title' => 'DNA Result',
        'page callback' => 'dna_display_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function dna_form() {
    $form['user_input'] = array(
        '#title' => 'Nucleotides',
        '#type' => 'textfield',
        '#description' => t('Enter any combination of the nucleotides A, T, C or G with no spaces.'),
        '#element_validate' => array('element_validate_input'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go',
    );
    return $form;
}


function element_validate_input($element) {
    $input = $element['#value'];
    $regex = '/([BD-FH-SU-Zbd-fh-su-z])/';
    if(ctype_alpha($input) === false || preg_match($regex, $input) === 1) {
        form_error($element, t('Please enter an allowed series of values (A, T, C or G).'));
    }
}

function dna_form_submit($form, &$form_state) {
    $input = strtoupper($form_state['values']['user_input']);
    $_SESSION['user_input'] = $input;
}


function dna_find_matches($user_nucleotides) {
    //create array of characters for user input
    $user_input = $_SESSION['user_input'];
    $input_characters = str_split($user_input);
    //create empty variable for results
    $result = '';
    //for each nucleotide in array
    foreach ($input_characters as $character) {
        //conditinal statement identifies nucleotide and matches it to its neccesary pair, then pushes paired nucleotide into results string
        if ($character === 'A') {
            $result .= 'T';
        } elseif ($character === 'T') {
            $result .= 'A';
        } elseif ($character === 'C') {
            $result .= 'G';
        } elseif ($character === 'G') {
            $result .= 'C';
        }
    }
    //create session variable key for results.
    $_SESSION['result'] = $result;
    //remember to add return statement of results string for test
    return $result;
}

function dna_display_result() {
    
}
